apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fileserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: fileserver
    spec:
      containers:
        - name: fileserver
          imagePullPolicy: "Always"
          image: "lsstsqre/sciplat-fileserver"
          env:
            - name: DEBUG
              value: "true"
          ports:
          - name: nfs
            containerPort: 2049
          securityContext:
            privileged: True
          volumeMounts:
            - name: storage
              mountPath: /exports
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: physpvc
