apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: firefly
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/proxy-body-size: "0m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: {{FIREFLY_ROUTE}}$1$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-Port 443;
      proxy_set_header X-Forwarded-Path {{FIREFLY_ROUTE}};
spec:
  tls:
  - hosts:
    - {{HOSTNAME}}
    secretName: tls
  rules:
  - host: {{HOSTNAME}}
    http:
      paths:
      - path: {{FIREFLY_ROUTE}}(/|$)(.*)
        backend:
          serviceName: firefly
          servicePort: 8080
